/**
 * DTOs for the `/ai/*` endpoints — aligned to `docs/openapi-academic-triage.yaml`.
 *
 * Both endpoints return `503 Service Unavailable` when the AI service is
 * disabled in the backend. The UI treats 503 as an expected functional state,
 * NOT as an application error.
 */

import type { PriorityEnum } from './request-api.types';

/** Request body for `POST /ai/suggest-classification`. */
export interface AiClassificationRequest {
  /** Descriptive text of the request. minLength: 10, maxLength: 2000. */
  description: string;
}

/** Response for `POST /ai/suggest-classification`. */
export interface AiClassificationResponse {
  /** AI-suggested request type name. */
  suggestedRequestType?: string;
  /** ID of the suggested type if it exists in the catalogue; null if no match. */
  suggestedRequestTypeId?: number | null;
  /** Suggested priority. */
  suggestedPriority?: PriorityEnum;
  /** Confidence score between 0.0 and 1.0. */
  confidence?: number;
  /** Textual reasoning from the model. */
  reasoning?: string;
}

/** Response for `GET /ai/summarize/{requestId}`. */
export interface AiSummaryResponse {
  requestId?: number;
  /** Textual summary of the status and history generated by the LLM. */
  summary?: string;
  /** Generation timestamp (ISO 8601). */
  generatedAt?: string;
}
